//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BobaTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplications
    {
        public int ApplicationId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Position { get; set; }
        public string Introduction { get; set; }
        public string CvFilePath { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
